### PR TITLE
feature: update navigation styles

### LINKED ISSUE #22: Navigation styles
This is being built in website-addons in https://github.com/carbon-design-system/carbon-website
image

on mobile view it should collsapse to sidebar and match carbon

### PR DESCRIPTION
**Pull request by alisonjoseph**
ref #22 

https://deploy-preview-36--design-website.netlify.com/teams

fyi @jeanservaas @designertyler @ryancaruthers

### TODO
- [ ] active styles on Approach
- [x] mobile styles

Do we need active styles on any of the drop down items?

### CODE REVIEW

**Comment by jeanservaas** [comment]
Hey lady, raaayaaaal quick:

Hover on that dropdown should be the #353535 (right now it's reading as #4c4c4c

image

**Comment by alisonjoseph** [comment]
oops! had a typo in my file so it wasn't getting that css rule. fixed!

**Comment by jeanservaas** [comment]
Couple things I missed:

- this font size should be 16px / 1 rem (it's .875 rem now) to align with IDL and us.

image

- also just make sure to vertically center align the hamburger with the IBM Design at mobile and tablet looks like it's riding a little high (worse in safari than chrome, but still high) and it's also getting pushed too far to the left (hover is a thin rectangle)

image



- I would check the height of the blue 60 bar... it looks like 4px right now... I know we are using 2px on our banner tabs... but since this is a top nav, it may need to be more prominent... I know digital (Watson health?) is using this pattern on top navs, I'd just check to align that height @eraymond25 ?


image

Our banner tabs:
image

**Comment by alisonjoseph** [comment]
Updated! Will wait to adjust the active border state until I get confirmation on what it should be. 2px or 4px?

**Comment by eraymond25** [comment]
@jeanservaas 
for digital when the blue bar is on the bottom it's 4px, and when the blue bar is on the top it's 3px. Would you like us to change it to 2px? 2 just seemed really small

**Comment by jeanservaas** [comment]
@eraymond25
No don’t change! That’s why I was checking with you, wasn’t sure what people were doing with that!

**Comment by alisonjoseph** [comment]
https://deploy-preview-36--design-website.netlify.com @dakahn this is what I was talking about with the nav if you have time to take a look.

**Comment by alisonjoseph** [comment]
@dakahn thanks so much for taking the time to look through this. I'll make the updates I can within this repo (2-4 I think?) and then open an issue in carbon-components-react for the issues that relate specifically to UI Shell. (1 & 5?)

**Pull request merged**
