### PR TITLE
fix(video): reloop muted overlay on end

### LINKED ISSUE #262: Landing page sizzle video ending....
@alisonjoseph  @jnm2377  Can we make the video either replay with the tint back over the top or just keep looping until user decides to pause it? Instead of if ending with these tiles to view more videos?? see attached. Sorry i didnt catch this earlier!

screen shot 2019-01-30 at 1 49 12 pm

### LINKED ISSUE #278: Console error related to video on homepage
```
player.es.js:977 Uncaught (in promise) Error: #0062ff does not meet minimum contrast ratio. We recommend using brighter colors. (You could try #3281ff instead.) See WCAG 2.0 guidelines: http://www.w3.org/TR/WCAG/#visual-audio-contrast
    at VM170 7-e0cefe6d842905ca5b02.js:1
    at Array.forEach (<anonymous>)
    at k (VM170 7-e0cefe6d842905ca5b02.js:1)
    at s (VM170 7-e0cefe6d842905ca5b02.js:1)
(anonymous) @ player.es.js:977
k @ player.es.js:976
s @ player.es.js:1101
```

screen shot 2019-01-31 at 2 15 37 pm

any ideas @jnm2377

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #262 
Closes #278 

**Changed**

- fixed video end bug

**Removed**

- custom vimeo controls color

### CODE REVIEW

**Comment by alisonjoseph** [comment]
I tested again, and it shows the above screen for a split second then replays. @RyanCaruthers I'll leave it up to you whether thats ok?

**Comment by alisonjoseph** [comment]
Oh can we make the cursor a hand when its over the overlay so its more obvious they can click it.

**Comment by RyanCaruthers** [comment]
+1 to all of Alisons points above

**Comment by jnm2377** [comment]
@RyanCaruthers @alisonjoseph I can definitely add the pointer cursor.
What about the replay? For reference, the Vimeo API has an event listener for when a video reaches the end, however it doesn't work if the video is set to loop over. On initial load, the video is set to loop over so that if a user never clicks the play button, it'll just keep playing with the overlay/on mute. Then when a user clicks play, I turn off the loop setting so it'll listen for the end of the video. At the end of the video, since the looping functionality is turned off, I reload the video with its original settings (muted/overlay/looping).

**Comment by alisonjoseph** [comment]
Soudns like vimeo adds those videos at the end then for some reason and we don't have a way to remove? lets merge this in once you add the cursor change and we can look in to the other issue later.

**Comment by alisonjoseph** [comment]
@sstrubberg can you check vimeo settings for the "outro" settings for this video.

**Pull request merged**
