### PR TITLE
Philosophy spacing

### LINKED ISSUE #139: [Philosophy] Remove side bar copy in mobile / tighten spacing
screen shot 2019-01-24 at 1 04 18 pm

### PR DESCRIPTION
**Pull request by alisonjoseph**
Closes #139

### CODE REVIEW

**Comment by RyanCaruthers** [comment]
spacing between last two sections is good, but between the first and second section its still Huge.

see attached


screen shot 2019-01-24 at 11 14 39 pm

**Comment by alisonjoseph** [comment]
Its the exact same spacing, its because that paragraph on the right is longer.

**Comment by RyanCaruthers** [comment]
ahhh can we move that paragraph on the right up then? that paragraph on the right should line up at the top with the first paragraph on the left

**Comment by alisonjoseph** [comment]
oh good catch! fixed, looks way better now

**Pull request merged**
