### PR TITLE
feat(video): adds custom component for landing page video

### LINKED ISSUE #56: Landing page video preview and scroll
I would like the video to autoplay with black transparent tint overlay and play button.

See example here:
https://www.instrument.com/

### LINKED ISSUE #247: Landing page Video layout
The video playing across the black and white split background is a little jarring, so we are moving the black background down a little bit past the frame of the video.... see attached...

screen shot 2019-01-29 at 10 53 08 am
screen shot 2019-01-29 at 10 53 18 am
screen shot 2019-01-29 at 10 53 26 am

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #56 
Closes #247 

**New**

- Adds overlay, ~~custom control button, pause/play functionality, etc.~~
- Adds initial click play
- Adds volume on initial click
- Adds muted loop after video ends
- uses vimeo's Player API for custom controls

**Working On**

- [x] still need to figure out how to add an event listener for when the Video has ended. The Vimeo API has a custom method for that (`line 12`); I tried adding it by using `componentDidMount` but it didn't work. 

**Testing/Reviewing**
- Test that initial play is unmuting and restarting video.
- Test that Vimeo controls are clickable after initial click (should be since overlay is removed).
- Ensure that when video ends, it loops over again with overlay/muted sound
- Test that spacebar also pauses/plays video

### CODE REVIEW

**Comment by alisonjoseph** [comment]
This is looking awesome!

Tested in FF and Chrome
- Video pauses, but do we want a pause button to show up on hover?
- space bar doesn't do anything but jump down the page in firefox, works in chrome
- Do we want the cursor to be the hand in the beginning to click the play button? 
- Does the play button need a hover state @RyanCaruthers ?
- video is looping, assuming this is related to adding an event listener when video ends?

**Comment by jnm2377** [comment]
> video is looping, assuming this is related to adding an event listener when video ends?

@alisonjoseph yes. Since we want it to go back to the muted-autoplay-overlay state, I want it to keep looping, but be able to mute it and remove the active class so it'll have the overlay. 

> Should i send you a pause button icon and progression bar visual?

@RyanCaruthers Yes please! My mistake, I thought we didn't want a pause button since the Instrument video example didn't have one. 

> Also the BLUE hover state of the play button needs to just apply to hovering over the button, NOT the entire video frame.

Will fix this. I had initially done the hover on the whole frame since I noticed that the video on Instrument.com can be clicked anywhere on the frame to pause/play. This video component also has that functionality since I set a transparent button to take up the whole screen (icon is centered within the button). I can leave that functionality in and just add the hover state to the icon and not the whole button so that users can still click anywhere on the frame if you want, or do you want them to only be able to click on the icons?

**Comment by RyanCaruthers** [comment]
@jnm2377 My fault completeIy, you are correct, lets leave the pause button off for now and try and add a similar progress bar that appears whenever the movie is paused like the instrument one.

_I can leave that functionality in and just add the hover state to the icon and not the whole button so that users can still click anywhere on the frame if you want_

Yes! I like this idea, leave that in for now and we can see how that all feels.

**Comment by RyanCaruthers** [comment]
@designertyler do we have a minimal looking progress bar for videos? Like the one that appears when pausing the video on this instrument site? https://www.instrument.com/

**Comment by designertyler** [comment]
@RyanCaruthers I'm not aware of a progress bar type of component for video. The only one I can think of is actually part of the video itself and used for a totally different need https://next.carbondesignsystem.com/guidelines/motion/overview#expressive

**Comment by RyanCaruthers** [comment]
@designertyler Ah ok, let me think on this for a little bit...

**Comment by RyanCaruthers** [comment]
@jnm2377 The current video in the deploy link above seems like a lot lower quality... very pixelated. is this just for the purpose of us testing this feature?

**Comment by RyanCaruthers** [comment]
@alisonjoseph 

@jnm2377 and I wrapped about my recent thoughts on the video and some UX feedback in mind. So here is the new plan to achieve for the video.

We are deleting the IDL play button in the center for now, but we will keep the auto tinted loop, and we will bring in the minimal Vimeo player component in the same way it is for IDL videos throughout the IDL site.

See link and attached... Thanks yall!

https://design-language-new.w3ibm.mybluemix.net/design/language/elements/motion



screen shot 2019-01-29 at 10 41 41 am

**Comment by jnm2377** [comment]
@RyanCaruthers I've refactored the video to allow Vimeo controls. I need to figure out why the play bar isn't showing up. Last time I asked @sstrubberg to disable it on Vimeo and that automatically updated the site video as well, but for some reason, updating it on Vimeo this time didn't update this video. But otherwise, the muted overlay/autoplay works and then restarts on click, as well as goes back to a muted overlay loop after the played video ends. However, one problem I noticed is that since we're enabling Vimeo controls again, when you hover on the video with the overlay on, it's not gonna show the controls because of the overlay. It won't show until after it's initially clicked. Another problem with this is that if the video overlay is on, users navigating via keyboard can still get to the vimeo controls and pause/play/expand the muted video. Working on adding a keydown event listener for that.

**Comment by jnm2377** [comment]
@RyanCaruthers the Netlify link above should be updated. Mine is at least. If not try clicking on details in the Netlify check.

**Comment by RyanCaruthers** [comment]
@jnm2377 Im actually digging all of this right now. I think for this type of application the minimal controls are functional enough!

**Comment by jnm2377** [comment]
@RyanCaruthers added a function that will remove the overlay/play the video unmuted if a user navigates to the video controls via keyboard while the overlay is still on. So that issue is solved! The only thing I can't change would be that the controls are still behind the overlay on initial load until the video is played. Idk what your feelings are about thought. Otherwise this should be done! 👍

**Comment by alisonjoseph** [comment]
This is looking so good! 🎉

**Comment by jnm2377** [comment]
@alisonjoseph Do you have any thoughts on the video controls under the overlay? The vimeo functionality is that they're not visible until you hover over the video, however when the video hasn't been played yet and the overlay is still on, they still don't show because technically you're hovering over the overlay and not the video. Idk if users would know to click to play otherwise.. @RyanCaruthers

**Comment by alisonjoseph** [comment]
I wonder if having the play button you had before on the overlay might be a good idea? 🙃  I agree people might not click otherwise.

**Comment by RyanCaruthers** [comment]
@jnm2377 Yeah i wonder if you could add back the IDL play button for the as a part of the overlay graphic, to sort of fake the play button on the initial click. Just use the grey static button graphic with no hover state.

**Comment by jnm2377** [comment]
@alisonjoseph @RyanCaruthers so video is updated with the play icon and black bg. But for some reason Netlify didn't do a check so the link above isn't updated.

**Comment by RyanCaruthers** [comment]
how does it look???!!!

**Comment by RyanCaruthers** [comment]
@jnm2377 @alisonjoseph Looks awesome yall!!! APPROVED!!!

**Pull request merged**
